name: ROM Build

on:
  workflow_dispatch:
    inputs:
      ROM_NAME:
        description: 'ROM_NAME (Only support Arrow,Lineage,PixelExperience,AOSPA,crDroid,Evolution-X. Other ROM please create an issue in this repository.)'
        required: true
      ANDROID_VERSION:
        description: 'ANDROID_VERSION (Only support 13,14)'
        required: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "ROM_NAME: ${{ github.event.inputs.ROM_NAME }}"
        echo "ANDROID_VERSION: ${{ github.event.inputs.ANDROID_VERSION }}"
        echo "::endgroup::"
