name: ROM Build

on:
  workflow_dispatch:
    inputs:
      ROM_NAME:
        description: 'ROM_NAME (Only support Arrow,Lineage,PixelExperience,AOSPA,crDroid,Evolution-X. Other ROM please create an issue in this repository.)'
        required: true
      ANDROID_VERSION:
        description: 'ANDROID_VERSION (Only support 13,14)'
        required: true
      BRAND_NAME:
        description: 'BRAND_NAME'
        required: true
      DEVICE_CODENAME:
        description: 'DEVICE_CODENAME'
        required: true
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
      COMMON_TREE_URL:
        description: 'COMMON_TREE_URL (if no common tree, leave blank)'
        required: false
      COMMON_TREE_BRANCH:
        description: 'COMMON_TREE_BRANCH (if no common tree, leave blank)'
        required: false
      COMMON_TREE_FOLDER_NAME:
        description: 'COMMON_TREE_FOLDER_NAME (if no common tree, leave blank)'
        required: false
      VENDOR_BLOBS_URL:
        description: 'VENDOR_BLOBS_URL'
        required: true
      VENDOR_BLOBS_BRANCH:
        description: 'VENDOR_BLOBS_BRANCH'
        required: true
