name: Greeting from Mona
on: 
    workflow_dispatch:

jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    steps:
    - name: Print a greeting
      run: |
        cd /home/localhost/ROM1
        ls
    - name: Print
      run: |
        ls
