name: Test
on:
  workflow_dispatch:

jobs:
  yourjob:
    runs-on: self-hosted

    steps:
      - name: Run script
        id: script
        run: |
          setOutput
          generated_variable="some value"
          echo "::setOutput name=generated_variable::$generated_variable"

      - name: Access generated variable from script
        run: |
          echo "Generated variable value: ${{ steps.script.outputs.generated_variable }}"
