name: Test
on: 
    workflow_dispatch:
      inputs:
        ROM_NAME:
          description: 'ROM_NAME (Only support Arrow,Lineage,PixelExperience,AOSPA,crDroid,Evolution-X. Other ROM please create an issue in this repository.)'
          required: true

jobs:
  my-job:
    name: My Job
    runs-on: self-hosted
    steps:
    - name: Set variable
      run: |
          if [ ${{ github.event.inputs.DEVICE_TREE_URL }} = "Arrow" ]; then
            echo
            ROM_PATCH="ROM1"
          else
            echo
            ROM_PATCH="ROM2"
          fi
          echo "::env PATCH=ROM_PATCH::$ROM_PATCH"

    - name: Print
      run: |
        echo $PATCH
