name: Test
on:
  workflow_dispatch:

jobs:
  yourjob:
    runs-on: self-hosted

    steps:
      - name: Set color
        id: color-selector
        run: |
          SELECTED_COLOR="green"
          echo "SELECTED_COLOR=$SELECTED_COLOR" >> "$GITHUB_OUTPUT"
        
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"
