name: Test
on:
  workflow_dispatch:

jobs:
  yourjob:
    runs-on: self-hosted

    steps:
      - name: Run script
        id: script
        run: |
          generated_variable="some value"
          echo "{generated_variable}={$generated_variable}" >> $GITHUB_OUTPUT

      - name: Access generated variable from script
        run: |
          echo "Generated variable value: ${{ steps.script.outputs.generated_variable }}"
